### ISSUE TITLE
Can not connect to unimaster2 - port 22 is not open

### ISSUE THREAD

**Issue by nurseiit** [jyi/CSE341#1]
Dear professor @jyi,

I've got a VPN set up via Pulse Secure and I'm able to connect to `uni06` server as below:

```
$ nmap -p 22 -Pn uni06.unist.ac.kr

Starting Nmap 7.80 ( https://nmap.org ) at 2020-04-18 22:25 +06
Nmap scan report for uni06.unist.ac.kr (10.0.2.95)
Host is up (0.44s latency).

PORT   STATE SERVICE
22/tcp open  ssh

Nmap done: 1 IP address (1 host up) scanned in 0.50 seconds
```

But the same procedure for `unimaster2` yields the following:
```
$ nmap -p 22 -Pn unimaster2.unist.ac.kr

Starting Nmap 7.80 ( https://nmap.org ) at 2020-04-18 22:22 +06
Nmap scan report for unimaster2.unist.ac.kr (10.0.2.94)
Host is up.

PORT   STATE    SERVICE
22/tcp filtered ssh

Nmap done: 1 IP address (1 host up) scanned in 2.11 seconds
```

Also, please let us use `GitHub Issues` for our queries regarding the class, just like what I'm doing here 😌
Because email isn't quite a good option and `Issues` can make everything transparent as they are public for everyone.

Thanks!

**Comment by jyi** [comment]
Please check out the new announcement.
